# Amostragem Aleatória
Um determinado número de elementos é retirado da população de forma aleatória.

In [23]:
import pandas as pd
import numpy as np

Carregando a base de dados.

In [4]:
df = pd.read_csv(r"C:\Users\marcf\OneDrive\Documentos\Ciencia de dados\materiais-de-apoio-pandas - Curso Edu\Materiais de Apoio\Materiais de apoio - Estatística Aplicada\covid19.csv")

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50982 entries, 0 to 50981
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   case_id             0 non-null      float64
 1   provincial_case_id  50982 non-null  int64  
 2   age                 50982 non-null  object 
 3   sex                 50982 non-null  object 
 4   health_region       50982 non-null  object 
 5   province            50982 non-null  object 
 6   country             50982 non-null  object 
 7   date_report         50982 non-null  object 
 8   report_week         50982 non-null  object 
 9   has_travel_history  1150 non-null   object 
 10  locally_acquired    574 non-null    object 
 11  case_source         50982 non-null  object 
dtypes: float64(1), int64(1), object(10)
memory usage: 4.7+ MB


In [11]:
df.head()

case_id  provincial_case_id    age     sex      health_region province  \
0      NaN                   1  50-59    Male            Toronto  Ontario   
1      NaN                   2  50-59  Female            Toronto  Ontario   
2      NaN                   1  40-49    Male  Vancouver Coastal       BC   
3      NaN                   3  20-29  Female   Middlesex-London  Ontario   
4      NaN                   2  50-59  Female  Vancouver Coastal       BC   

  country date_report report_week has_travel_history locally_acquired  \
0  Canada  2020-01-25  2020-01-19                  t              NaN   
1  Canada  2020-01-27  2020-01-26                  t              NaN   
2  Canada  2020-01-28  2020-01-26                  t              NaN   
3  Canada  2020-01-31  2020-01-26                  t              NaN   
4  Canada  2020-02-04  2020-02-02                  f    Close Contact   

                                         case_source  
0  (1) https://news.ontario.ca/mohltc/en/2020/01/...  
1  (1) https://news.ontario.ca/mohltc/en/2020/01/...  
2  https://news.gov.bc.ca/releases/2020HLTH0015-0...  
3  (1) https://news.ontario.ca/mohltc/en/2020/01/...  
4  https://news.gov.bc.ca/releases/2020HLTH0023-0...

Criando uma amostra com apenas 1000 registros a partir do conjunto de dados.

In [5]:
df_sample = df.sample(n=1000)

In [12]:
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5098 entries, 18552 to 38256
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   case_id             0 non-null      float64
 1   provincial_case_id  5098 non-null   int64  
 2   age                 5098 non-null   object 
 3   sex                 5098 non-null   object 
 4   health_region       5098 non-null   object 
 5   province            5098 non-null   object 
 6   country             5098 non-null   object 
 7   date_report         5098 non-null   object 
 8   report_week         5098 non-null   object 
 9   has_travel_history  118 non-null    object 
 10  locally_acquired    61 non-null     object 
 11  case_source         5098 non-null   object 
dtypes: float64(1), int64(1), object(10)
memory usage: 517.8+ KB


Especificando o tamanho da amostra através do percentual.

In [6]:
df_sample = df.sample(frac=0.10)

In [13]:
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5098 entries, 18552 to 38256
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   case_id             0 non-null      float64
 1   provincial_case_id  5098 non-null   int64  
 2   age                 5098 non-null   object 
 3   sex                 5098 non-null   object 
 4   health_region       5098 non-null   object 
 5   province            5098 non-null   object 
 6   country             5098 non-null   object 
 7   date_report         5098 non-null   object 
 8   report_week         5098 non-null   object 
 9   has_travel_history  118 non-null    object 
 10  locally_acquired    61 non-null     object 
 11  case_source         5098 non-null   object 
dtypes: float64(1), int64(1), object(10)
memory usage: 517.8+ KB


# Amostragem aleatória Estratificada
importando o método train_test_split para fazer a amostragem.

In [7]:
from sklearn.model_selection import train_test_split

Contagem de registro

In [14]:
df['province'].value_counts()

Quebec           25757
Ontario          16337
Alberta           4850
BC                2053
Nova Scotia        915
Saskatchewan       366
Manitoba           272
NL                 258
New Brunswick      118
PEI                 27
Repatriated         13
Yukon               11
NWT                  5
Name: province, dtype: int64

Gerando a amostragem estratificada.

In [15]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('province',axis=1),
                                                    df['province'],
                                                    stratify=df['province'],
                                                    test_size=0.20)

In [16]:
y_test.shape

(10197,)

In [17]:
y_test.value_counts()

Quebec           5152
Ontario          3267
Alberta           970
BC                411
Nova Scotia       183
Saskatchewan       73
Manitoba           54
NL                 52
New Brunswick      24
PEI                 5
Repatriated         3
Yukon               2
NWT                 1
Name: province, dtype: int64

Gerando a semente aleatória

In [24]:
seed = np.random.choice(10,1)

In [25]:
seed

array([5])

Gerando índices a partir da semente

In [26]:
index = np.arange(0,100,seed)

In [27]:
index2 = np.arange(0,len(df),seed)

In [28]:
index

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [29]:
index2

array([    0,     5,    10, ..., 50970, 50975, 50980])

Gerando amostras a partir dos índices

In [30]:
amostra = df.loc[index,:]
amostra

case_id  provincial_case_id           age           sex  \
0       NaN                   1         50-59          Male   
5       NaN                   3         30-39          Male   
10      NaN                   5         60-69        Female   
15      NaN                   8         80-89          Male   
20      NaN                  12         50-59          Male   
25      NaN                  17         70-79        Female   
30      NaN                  10         60-69          Male   
35      NaN                  21         50-59        Female   
40      NaN                  16         50-59        Female   
45      NaN                  21         50-59        Female   
50      NaN                   3  Not Reported  Not Reported   
55      NaN                  23         60-69          Male   
60      NaN                  29         40-49        Female   
65      NaN                  31         60-69          Male   
70      NaN                  29         50-59          Male   
75      NaN                   6         30-39          Male   
80      NaN                   8         70-79          Male   
85      NaN                  13         30-39        Female   
90      NaN                  36         90-99          Male   
95      NaN                  38         30-39        Female   

        health_region province country date_report report_week  \
0             Toronto  Ontario  Canada  2020-01-25  2020-01-19   
5   Vancouver Coastal       BC  Canada  2020-02-06  2020-02-02   
10            Toronto  Ontario  Canada  2020-02-26  2020-02-23   
15            Toronto  Ontario  Canada  2020-02-28  2020-02-23   
20               York  Ontario  Canada  2020-03-01  2020-03-01   
25            Toronto  Ontario  Canada  2020-03-03  2020-03-01   
30  Vancouver Coastal       BC  Canada  2020-03-03  2020-03-01   
35           Waterloo  Ontario  Canada  2020-03-05  2020-03-01   
40  Vancouver Coastal       BC  Canada  2020-03-05  2020-03-01   
45             Fraser       BC  Canada  2020-03-05  2020-03-01   
50         Montérégie   Quebec  Canada  2020-03-06  2020-03-01   
55             Fraser       BC  Canada  2020-03-07  2020-03-01   
60            Toronto  Ontario  Canada  2020-03-08  2020-03-08   
65            Toronto  Ontario  Canada  2020-03-08  2020-03-08   
70             Fraser       BC  Canada  2020-03-09  2020-03-08   
75            Calgary  Alberta  Canada  2020-03-09  2020-03-08   
80           Edmonton  Alberta  Canada  2020-03-09  2020-03-08   
85            Calgary  Alberta  Canada  2020-03-09  2020-03-08   
90  Vancouver Coastal       BC  Canada  2020-03-10  2020-03-08   
95               York  Ontario  Canada  2020-03-11  2020-03-08   

   has_travel_history locally_acquired  \
0                   t              NaN   
5                   t              NaN   
10                  t              NaN   
15                  t              NaN   
20                  t              NaN   
25                  t              NaN   
30                  t              NaN   
35                  t              NaN   
40                  f    Close Contact   
45                  f        Community   
50                  t              NaN   
55                  t              NaN   
60                  t              NaN   
65                  t              NaN   
70                  f    Close Contact   
75                  t              NaN   
80                  t              NaN   
85                  t              NaN   
90                  t              NaN   
95                  t              NaN   

                                          case_source  
0   (1) https://news.ontario.ca/mohltc/en/2020/01/...  
5   https://news.gov.bc.ca/releases/2020HLTH0025-0...  
10  (1) https://news.ontario.ca/mohltc/en/2020/02/...  
15  https://news.ontario.ca/mohltc/en/2020/02/onta...  
20  (1) https://news.ontario.ca/mohltc/en/2020/03/...  
25  https://toronto.ctvnews.ca/three-new-cases-of-...  
30  https://news.g

In [31]:
amostra2 = df.loc[index2,:]
amostra2

case_id  provincial_case_id           age           sex  \
0          NaN                   1         50-59          Male   
5          NaN                   3         30-39          Male   
10         NaN                   5         60-69        Female   
15         NaN                   8         80-89          Male   
20         NaN                  12         50-59          Male   
...        ...                 ...           ...           ...   
50960      NaN               16316  Not Reported  Not Reported   
50965      NaN               16321  Not Reported  Not Reported   
50970      NaN               16326  Not Reported  Not Reported   
50975      NaN               16331  Not Reported  Not Reported   
50980      NaN               16336  Not Reported  Not Reported   

           health_region province country date_report report_week  \
0                Toronto  Ontario  Canada  2020-01-25  2020-01-19   
5      Vancouver Coastal       BC  Canada  2020-02-06  2020-02-02   
10               Toronto  Ontario  Canada  2020-02-26  2020-02-23   
15               Toronto  Ontario  Canada  2020-02-28  2020-02-23   
20                  York  Ontario  Canada  2020-03-01  2020-03-01   
...                  ...      ...     ...         ...         ...   
50960               York  Ontario  Canada  2020-04-28  2020-04-26   
50965               York  Ontario  Canada  2020-04-28  2020-04-26   
50970               York  Ontario  Canada  2020-04-28  2020-04-26   
50975               York  Ontario  Canada  2020-04-28  2020-04-26   
50980       Peterborough  Ontario  Canada  2020-04-28  2020-04-26   

      has_travel_history locally_acquired  \
0                      t              NaN   
5                      t              NaN   
10                     t              NaN   
15                     t              NaN   
20                     t              NaN   
...                  ...              ...   
50960                NaN              NaN   
50965                NaN              NaN   
50970                NaN              NaN   
50975                NaN              NaN   
50980                NaN              NaN   

                                             case_source  
0      (1) https://news.ontario.ca/mohltc/en/2020/01/...  
5      https://news.gov.bc.ca/releases/2020HLTH0025-0...  
10     (1) https://news.ontario.ca/mohltc/en/2020/02/...  
15     https://news.ontario.ca/mohltc/en/2020/02/onta...  
20     (1) https://news.ontario.ca/mohltc/en/2020/03/...  
...                                                  ...  
50960  https://www.york.ca/wps/portal/yorkhome/health...  
50965  https://www.york.ca/wps/portal/yorkhome/health...  
50970  https://www.york.ca/wps/portal/yorkhome/health...  
50975  https://www.york.ca/wps/portal/yorkhome/health...  
50980  https://www.peterboroughpublichealth.ca/your-h...  

[10197 rows x 12 columns]

In [32]:
amostra.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20 entries, 0 to 95
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   case_id             0 non-null      float64
 1   provincial_case_id  20 non-null     int64  
 2   age                 20 non-null     object 
 3   sex                 20 non-null     object 
 4   health_region       20 non-null     object 
 5   province            20 non-null     object 
 6   country             20 non-null     object 
 7   date_report         20 non-null     object 
 8   report_week         20 non-null     object 
 9   has_travel_history  20 non-null     object 
 10  locally_acquired    3 non-null      object 
 11  case_source         20 non-null     object 
dtypes: float64(1), int64(1), object(10)
memory usage: 2.0+ KB
