<a href="https://colab.research.google.com/github/Marcfeitosa/Data-Science-Projects/blob/main/Python_para_an%C3%A1lise_de_dados_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importando a bilbioteca numpy
import numpy as np

In [ ]:
# Criano um array de 1 dimensão
one_dim = np.array([1,2,3,4])

In [ ]:
type(one_dim)

numpy.ndarray

In [ ]:
# Imprimindo um array
one_dim.ndim

1

In [ ]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Cria um arrau de números aleatórios.
# Um array de 5 linhas e duas dimensões.
np.random.random((5,2))

array([[0.10654109, 0.20565609],
       [0.06041236, 0.57045303],
       [0.8112946 , 0.60896359],
       [0.36090107, 0.11040882],
       [0.67229151, 0.48829919]])

In [ ]:
#Cria um array com valores esparsos iniciando com o valor 10, menor que 50 e incrementando d 5 em 5
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
#Cria um array linear de 0 a 2 de no máximo 9 elementos.
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
#Cria um array de valores zero.
#Cria um array com 3 linhas e 4 dimensões.
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

##Numpy Arrays Vs Listas


*   Arrays Numpy permitem fazemos operações em arrays inteiros de forma rápida
*   Listas não permitem operações em todos os elementos da lista
*   Para operações em todos os elementos é preciso iterar sobre toa a lista.
*   Listas em Python armazenam diferentes tipos de objetos
*   Arrays Numpy considera todos os elementos de tipos distintos como strings


In [ ]:
#Criando uma lista em Python.
lista = [1,2,3]

In [ ]:
lista

array([1, 2, 3])

In [ ]:
# Multiplica valores da lista por 2.
lista * 2

[1, 2, 3, 1, 2, 3]

In [ ]:
#Transformando a variável lista em um array Numpy
lista = np.array(lista)

In [ ]:
lista

array([1, 2, 3])

In [ ]:
type(lista)

numpy.ndarray

In [ ]:
#multiplicando cada elemento po 2
lista * 2

array([2, 4, 6])

In [ ]:
#calcular IMC de pessoas

pesos = [67,81,120,90]
alturas = [1.68, 1.70, 1.75, 1.85]

In [ ]:
#transformando as listas em arrays Numpy

pesos = np.array(pesos)
alturas = np.array(alturas)

In [ ]:
#Faz o cálculo usando as listas
pesos / alturas ** 2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [ ]:
# arraus Numpy armazenam elementos como Strings quando estes não são inteiros ou float
a = np.array([1,3,'casa',True])

In [ ]:
a

array(['1', '3', 'casa', 'True'], dtype='<U21')

In [ ]:
a * 2

UFuncTypeError: ignored

## Métodos e Atributos

In [ ]:
# Métodos disponívels (digite o . pressione tab)
two_dim.

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
two_dim.shape

(2, 3)

In [ ]:
two_dim.ndim

2

In [ ]:
two_dim.max()

6

In [ ]:
two_dim.min()

1

In [ ]:
two_dim.mean()

3.5

In [ ]:
# Imprime o desvio padrão

two_dim.std()

1.707825127659933

In [ ]:
two_dim.dtype

dtype('int64')

In [ ]:
two_dim.size

6

In [ ]:
# Mostra a quantidade de itens em bites
two_dim.itemsize

8

In [ ]:
# Somando todos os elementos do array
two_dim.sum()

21

## Transformando Arrays

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Gera a transposta da Matriz (linha -> coluna)
two_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# Transforma em uma matriz de uma linha.
# É muito comum em bilbiotecas como Scikit-learn e Keras
two_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
tree = np.random.random((5,3))

In [ ]:
tree.shape

(5, 3)

In [ ]:
# Transforma em uma matriz com 3 linhas e 5 colunas

In [ ]:
tree.reshape(3,5)

array([[0.51255175, 0.47622013, 0.85326859, 0.36106956, 0.91291428],
       [0.41218476, 0.46162412, 0.42588981, 0.07434782, 0.55124538],
       [0.46482471, 0.43802625, 0.57007955, 0.49889969, 0.51148943]])

In [ ]:
tree.reshape(-1).shape

(15,)

In [ ]:
t=tree.reshape(1,15)
t.shape

(1, 15)

In [ ]:
t=tree.reshape(1,15)
t

array([[0.51255175, 0.47622013, 0.85326859, 0.36106956, 0.91291428,
        0.41218476, 0.46162412, 0.42588981, 0.07434782, 0.55124538,
        0.46482471, 0.43802625, 0.57007955, 0.49889969, 0.51148943]])

In [ ]:
tree.reshape(-1)

array([0.51255175, 0.47622013, 0.85326859, 0.36106956, 0.91291428,
       0.41218476, 0.46162412, 0.42588981, 0.07434782, 0.55124538,
       0.46482471, 0.43802625, 0.57007955, 0.49889969, 0.51148943])

In [ ]:
two_dim

array([10,  1,  2,  3,  4,  5,  6])

In [ ]:
#Adicionando elementos a um array
two_dim = np.insert(two_dim,0,10)

In [ ]:
#Transforma em um array de uma linha.
two_dim

array([10,  1,  2,  3,  4,  5,  6])

In [ ]:
# Apagando o elemento da primeira posição do array
two_dim = np.delete(two_dim,[0])

In [ ]:
two_dim

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Gerando um arquivo TXT a partir de um array

np.savetxt('dataset_array.txt',two_dim, delimiter=',')

#Acesando Dimensões no Array

In [ ]:
# Gera um array aleatório de 10 linhas e 2 colunas
# formato linha, coluna
my_array = np.random.random([10,2])

In [ ]:
my_array

array([[0.66262994, 0.04502982],
       [0.31991077, 0.88142963],
       [0.06660147, 0.98032439],
       [0.66031139, 0.8410686 ],
       [0.28012098, 0.95188981],
       [0.20741093, 0.46729239],
       [0.72842947, 0.65422307],
       [0.47324511, 0.30950075],
       [0.5253363 , 0.76142683],
       [0.99557049, 0.03669946]])

In [ ]:
# Imprimindo o primeiro elemento (1 linha)
my_array[0]

array([0.66262994, 0.04502982])

In [ ]:
#Imprimindo o primeiro elemento da coluna 0 (1ª coluna)

my_array[0][0]

0.6626299441815777

In [ ]:
# Iimprimindo o elemento da coluna 1
my_array[0][1]

0.04502981809636808

In [ ]:
# imprimindo o segundo elemento da coluna 1
my_array[1][1]

0.8814296338633933

In [ ]:
#Imprimindo o segundo elemento da coluna escrito com vírgula.
# O primeiro valor especifica a linha e o segundo valor especifica a coluna.
my_array[1,1]

0.8814296338633933

In [ ]:
# Imprimindo até 3 valores da coluna 1
my_array[:3,1]

array([0.04502982, 0.88142963, 0.98032439])

In [ ]:
# Imprimindo todas as linhas da coluna 2 * 10
my_array[:,1] * 10

array([0.45029818, 8.81429634, 9.80324393, 8.41068604, 9.51889805,
       4.67292385, 6.54223072, 3.09500752, 7.61426828, 0.36699457])

In [ ]:
# Comparação retorna indices
my_array > 0.50

array([[ True, False],
       [False,  True],
       [False,  True],
       [ True,  True],
       [False,  True],
       [False, False],
       [ True,  True],
       [False, False],
       [ True,  True],
       [ True, False]])

In [ ]:
# Acessando os valores por indices
my_array[my_array > 0.50]

array([0.66262994, 0.88142963, 0.98032439, 0.66031139, 0.8410686 ,
       0.95188981, 0.72842947, 0.65422307, 0.5253363 , 0.76142683,
       0.99557049])

##Carregar Arrays Numpy a partir de arquivos de Texto

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Lendo um arquivo do tipo .txt (arquivo já criado acima, para puxar esse arquivo é só rodá-lo outra vez)
dataset = np.loadtxt('/content/dataset_array.txt', delimiter=',')

In [ ]:
dataset.shape

(6,)

In [ ]:
dataset

array([1., 2., 3., 4., 5., 6.])

In [ ]:
# Carregando um arquivo dividido em 3 arrays
a,b,c = np.loadtxt('/content/dataset_valores.csv', skiprows=1, unpack=True)

In [ ]:
# Array a
a

array([0.4839, 0.1292, 0.1781, 0.7676, 0.5993])

In [ ]:
# Array b
b

array([0.4536, 0.6875, 0.3049, 0.5801, 0.4357])

In [ ]:
# Array c
c

array([0.3561, 0.6565, 0.8928, 0.2038, 0.741 ])

In [ ]:
# Carrega o arquivo ignorando as 2 primeiras linhas e preenchendo os valores vazios por 0
# Obs: os valores string também são convertidos!!
# para dar certo no Colab os valores precisam ser alterados no arquivo txt e salvos no formato .csv

dataset = np.genfromtxt('/content/dataset_valores_vazio.csv', skip_header=1, filling_values=0)

In [ ]:
#Imprimendo o dataset
dataset

array([[0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.    ],
       [0.1781, 0.3049, 0.8928],
       [0.    , 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])