<a href="https://colab.research.google.com/github/Marcfeitosa/Data-Science-Projects/blob/main/Tecnicas_Amostragem_Dados_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Amostragem Aleatória

Um determinado número de elementos é retirado da população de forma aleatória.

In [ ]:
import pandas as pd
import numpy as np

Carregando a base de dados.

In [ ]:
df=pd.read_csv('sample_data/covid19.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47033 entries, 0 to 47032
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   case_id             0 non-null      float64
 1   provincial_case_id  47033 non-null  int64  
 2   age                 47033 non-null  object 
 3   sex                 47033 non-null  object 
 4   health_region       47033 non-null  object 
 5   province            47033 non-null  object 
 6   country             47032 non-null  object 
 7   date_report         47032 non-null  object 
 8   report_week         47032 non-null  object 
 9   has_travel_history  1123 non-null   object 
 10  locally_acquired    547 non-null    object 
 11  case_source         47032 non-null  object 
dtypes: float64(1), int64(1), object(10)
memory usage: 4.3+ MB


In [ ]:
df.head()

case_id  provincial_case_id    age     sex      health_region province  \
0      NaN                   1  50-59    Male            Toronto  Ontario   
1      NaN                   2  50-59  Female            Toronto  Ontario   
2      NaN                   1  40-49    Male  Vancouver Coastal       BC   
3      NaN                   3  20-29  Female   Middlesex-London  Ontario   
4      NaN                   2  50-59  Female  Vancouver Coastal       BC   

  country date_report report_week has_travel_history locally_acquired  \
0  Canada  2020-01-25  2020-01-19                  t              NaN   
1  Canada  2020-01-27  2020-01-26                  t              NaN   
2  Canada  2020-01-28  2020-01-26                  t              NaN   
3  Canada  2020-01-31  2020-01-26                  t              NaN   
4  Canada  2020-02-04  2020-02-02                  f    Close Contact   

                                         case_source  
0  (1) https://news.ontario.ca/mohltc/en/2020/01/...  
1  (1) https://news.ontario.ca/mohltc/en/2020/01/...  
2  https://news.gov.bc.ca/releases/2020HLTH0015-0...  
3  (1) https://news.ontario.ca/mohltc/en/2020/01/...  
4  https://news.gov.bc.ca/releases/2020HLTH0023-0...

Criando uma amostra com apenas 1000 registros a partir do conjunto de dados.

In [ ]:
df_sample = df.sample(n=1000)

In [ ]:
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 23413 to 10293
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   case_id             0 non-null      float64
 1   provincial_case_id  1000 non-null   int64  
 2   age                 1000 non-null   object 
 3   sex                 1000 non-null   object 
 4   health_region       1000 non-null   object 
 5   province            1000 non-null   object 
 6   country             1000 non-null   object 
 7   date_report         1000 non-null   object 
 8   report_week         1000 non-null   object 
 9   has_travel_history  15 non-null     object 
 10  locally_acquired    10 non-null     object 
 11  case_source         1000 non-null   object 
dtypes: float64(1), int64(1), object(10)
memory usage: 101.6+ KB


Especificando o tamanho da amostra através do percentual.

In [ ]:
df_sample = df.sample(frac=0.10)

In [ ]:
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4703 entries, 45675 to 42606
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   case_id             0 non-null      float64
 1   provincial_case_id  4703 non-null   int64  
 2   age                 4703 non-null   object 
 3   sex                 4703 non-null   object 
 4   health_region       4703 non-null   object 
 5   province            4703 non-null   object 
 6   country             4703 non-null   object 
 7   date_report         4703 non-null   object 
 8   report_week         4703 non-null   object 
 9   has_travel_history  90 non-null     object 
 10  locally_acquired    44 non-null     object 
 11  case_source         4703 non-null   object 
dtypes: float64(1), int64(1), object(10)
memory usage: 477.6+ KB


# Amostragem aleatória Estratificada

importando o método train_test_split para fazer a amostragem.

In [ ]:
from sklearn.model_selection import train_test_split

Contagem de registro

In [ ]:
df['province'].value_counts()

Quebec           23765
Ontario          14915
Alberta           4480
BC                1948
Nova Scotia        873
Saskatchewan       349
Manitoba           271
NL                 258
New Brunswick      118
PEI                 26
Repatriated         13
Yukon               11
NWT                  5
Queb                 1
Name: province, dtype: int64

Gerando a amostragem estratificada.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('province',axis=1),
                                                    df['province'],
                                                    test_size=0.20)


Verificando a forma dos dados

In [ ]:
y_test.shape

(11759,)

In [ ]:
y_test.value_counts()

Quebec           5887
Ontario          3793
Alberta          1100
BC                475
Nova Scotia       227
Saskatchewan       85
NL                 83
Manitoba           66
New Brunswick      29
Yukon               4
PEI                 4
Repatriated         4
NWT                 2
Name: province, dtype: int64

Gerando a semente aleatória

In [ ]:
seed = np.random.choice(10,1)

In [ ]:
seed

array([5])

Gerando índices a partir da semente

In [ ]:
index = np.arange(0,100,seed)

In [ ]:
index2 = np.arange(0,len(df),seed)

In [ ]:
index

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
index2

array([    0,     5,    10, ..., 47020, 47025, 47030])

Gerando amostras a partir dos índices

In [ ]:
amostra = df.loc[index,:]
amostra

case_id  provincial_case_id           age           sex  \
0       NaN                   1         50-59          Male   
1       NaN                   2         50-59        Female   
2       NaN                   1         40-49          Male   
3       NaN                   3         20-29        Female   
4       NaN                   2         50-59        Female   
..      ...                 ...           ...           ...   
95      NaN                  38         30-39        Female   
96      NaN                  39         30-39          Male   
97      NaN                  40         40-49          Male   
98      NaN                  41         30-39        Female   
99      NaN                   6  Not Reported  Not Reported   

        health_region province country date_report report_week  \
0             Toronto  Ontario  Canada  2020-01-25  2020-01-19   
1             Toronto  Ontario  Canada  2020-01-27  2020-01-26   
2   Vancouver Coastal       BC  Canada  2020-01-28  2020-01-26   
3    Middlesex-London  Ontario  Canada  2020-01-31  2020-01-26   
4   Vancouver Coastal       BC  Canada  2020-02-04  2020-02-02   
..                ...      ...     ...         ...         ...   
95               York  Ontario  Canada  2020-03-11  2020-03-08   
96            Toronto  Ontario  Canada  2020-03-11  2020-03-08   
97             Ottawa  Ontario  Canada  2020-03-11  2020-03-08   
98             Halton  Ontario  Canada  2020-03-11  2020-03-08   
99           Montréal   Quebec  Canada  2020-03-11  2020-03-08   

   has_travel_history locally_acquired  \
0                   t              NaN   
1                   t              NaN   
2                   t              NaN   
3                   t              NaN   
4                   f    Close Contact   
..                ...              ...   
95                  t              NaN   
96                  t              NaN   
97                  t              NaN   
98                  t              NaN   
99                  t              NaN   

                                          case_source  
0   (1) https://news.ontario.ca/mohltc/en/2020/01/...  
1   (1) https://news.ontario.ca/mohltc/en/2020/01/...  
2   https://news.gov.bc.ca/releases/2020HLTH0015-0...  
3   (1) https://news.ontario.ca/mohltc/en/2020/01/...  
4   https://news.gov.bc.ca/releases/2020HLTH0023-0...  
..                                                ...  
95  https://www.ontario.ca/page/2019-novel-coronav...  
96  https://www.ontario.ca/page/2019-novel-coronav...  
97  [1] https://www.ontario.ca/page/2019-novel-cor...  
98  [1] https://www.ontario.ca/page/2019-novel-cor...  
99  (1) https://www.lapresse.ca/covid-19/202003/11...  

[100 rows x 12 columns]

In [ ]:
amostra2 = df.loc[index2,:]
amostra2

case_id  provincial_case_id           age           sex  \
0          NaN                   1         50-59          Male   
5          NaN                   3         30-39          Male   
10         NaN                   5         60-69        Female   
15         NaN                   8         80-89          Male   
20         NaN                  12         50-59          Male   
...        ...                 ...           ...           ...   
47010      NaN               23744  Not Reported  Not Reported   
47015      NaN               23749  Not Reported  Not Reported   
47020      NaN               23754  Not Reported  Not Reported   
47025      NaN               23759  Not Reported  Not Reported   
47030      NaN               23764  Not Reported  Not Reported   

           health_region province country date_report report_week  \
0                Toronto  Ontario  Canada  2020-01-25  2020-01-19   
5      Vancouver Coastal       BC  Canada  2020-02-06  2020-02-02   
10               Toronto  Ontario  Canada  2020-02-26  2020-02-23   
15               Toronto  Ontario  Canada  2020-02-28  2020-02-23   
20                  York  Ontario  Canada  2020-03-01  2020-03-01   
...                  ...      ...     ...         ...         ...   
47010           Montréal   Quebec  Canada  2020-04-26  2020-04-26   
47015           Montréal   Quebec  Canada  2020-04-26  2020-04-26   
47020           Montréal   Quebec  Canada  2020-04-26  2020-04-26   
47025           Montréal   Quebec  Canada  2020-04-26  2020-04-26   
47030           Montréal   Quebec  Canada  2020-04-26  2020-04-26   

      has_travel_history locally_acquired  \
0                      t              NaN   
5                      t              NaN   
10                     t              NaN   
15                     t              NaN   
20                     t              NaN   
...                  ...              ...   
47010                NaN              NaN   
47015                NaN              NaN   
47020                NaN              NaN   
47025                NaN              NaN   
47030                NaN              NaN   

                                             case_source  
0      (1) https://news.ontario.ca/mohltc/en/2020/01/...  
5      https://news.gov.bc.ca/releases/2020HLTH0025-0...  
10     (1) https://news.ontario.ca/mohltc/en/2020/02/...  
15     https://news.ontario.ca/mohltc/en/2020/02/onta...  
20     (1) https://news.ontario.ca/mohltc/en/2020/03/...  
...                                                  ...  
47010  https://www.quebec.ca/sante/problemes-de-sante...  
47015  https://www.quebec.ca/sante/problemes-de-sante...  
47020  https://www.quebec.ca/sante/problemes-de-sante...  
47025  https://www.quebec.ca/sante/problemes-de-sante...  
47030  https://www.quebec.ca/sante/problemes-de-sante...  

[9407 rows x 12 columns]

Contagem de registros

In [ ]:
amostra.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   case_id             0 non-null      float64
 1   provincial_case_id  100 non-null    int64  
 2   age                 100 non-null    object 
 3   sex                 100 non-null    object 
 4   health_region       100 non-null    object 
 5   province            100 non-null    object 
 6   country             100 non-null    object 
 7   date_report         100 non-null    object 
 8   report_week         100 non-null    object 
 9   has_travel_history  100 non-null    object 
 10  locally_acquired    22 non-null     object 
 11  case_source         100 non-null    object 
dtypes: float64(1), int64(1), object(10)
memory usage: 10.2+ KB
